image: ruby:3.4.11 # better to pin version rather than use ruby:latest https://github.com/ruby/ruby/releases

before_script:
  - apt-get update -qy
  - apt-get install -y nodejs

  - gem cleanup
  - gem install jekyll
  - gem install bundler
  - bundle install

pages:
  stage: deploy
  variables:
    FF_USE_FASTZIP: "true"
    ARTIFACT_COMPRESSION_LEVEL: "fastest"
  script:
  - bundle exec jekyll build -d public
  # - JEKYLL_ENV=production bundle exec jekyll build -d public # runs jekyll in production mode (no longer needed)
  artifacts:
    paths:
    - public
  # This will make it build the website only when a new tag is pushed. Note that `rules:` does not work with `only:` so the latter is removed.
  #only:
  #- master
  rules:
  - if: $CI_COMMIT_TAG
  interruptible: true

cache:
  paths:
    - vendor/

# Note: The two flags:
#FF_USE_FASTZIP: "true"
#ARTIFACT_COMPRESSION_LEVEL: "fastest"
# Are necessary for [HTTP Range requests], which is essential for features like seeking or skipping in videos
